language: python
sudo: false

python:
  - "2.7"
  - "3.5"

cache:
  - apt
  - directories:
    - $HOME/.cache/pip  # makes things go fast 2nd time around!

notifications:
  email: false

before_install: # Setup anaconda
  - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - export PATH=$PATH:$HOME/miniconda2/bin
  - export PYTHONPATH=$HOME/miniconda2/lib/python$TRAVIS_PYTHON_VERSION/site-packages/:$PYTHONPATH
  - conda update --yes conda
  - conda install --yes python=$TRAVIS_PYTHON_VERSION numpy scipy
  - "pip install python-coveralls coverage setuptools"

install: # Install packages
  - "pip install -r requirements.txt"
  - "python setup.py install"

script: # Run test
  - nosetests ping --with-coverage

after_success: # Calculate coverage
  - coveralls --config_file .coveragerc
